// Генерирано 1:1 от CRM_Visual_Master_Board_Imoti_Nadezhda_v17_FULL_PREVIEW.html.
// Не редактирай ръчно — таблицата е MASTER референция.

export type MasterBoardQuarterRef = {
  name: string;
  slug: string;
  src: string;
};

export type MasterBoardRow = {
  num: string;
  category: string;
  page: string;
  path: string;
  route: string;
  statusKind: "ok" | "waiting";
  statusLabel: string;
  approvedByDefault: boolean;
  desktop: string | null;
  desktopLabel: string;
  mobile: string | null;
  mobileLabel: string;
  /** Допълнителни квартални референции (по желание). */
  quarterRefs?: MasterBoardQuarterRef[];
};

/** 28 квартални референции за Шумен (ред 05). */
export const SHUMEN_QUARTER_REFS: MasterBoardQuarterRef[] = [
  {
    name: "Център",
    slug: "centar",
    src: "/master-board/quarters/shumen/centar.svg",
  },
  {
    name: "Тракия",
    slug: "trakiya",
    src: "/master-board/quarters/shumen/trakiya.svg",
  },
  {
    name: "Добруджански",
    slug: "dobrudjanski",
    src: "/master-board/quarters/shumen/dobrudjanski.svg",
  },
  {
    name: "Пазара",
    slug: "pazara",
    src: "/master-board/quarters/shumen/pazara.svg",
  },
  {
    name: "Болницата",
    slug: "bolnicata",
    src: "/master-board/quarters/shumen/bolnicata.svg",
  },
  {
    name: "Пети полк",
    slug: "peti-polk",
    src: "/master-board/quarters/shumen/peti-polk.svg",
  },
  {
    name: "Военно училище",
    slug: "voenno-uchilishte",
    src: "/master-board/quarters/shumen/voenno-uchilishte.svg",
  },
  {
    name: "Боян Българанов 2",
    slug: "boyan-bulgarov-2",
    src: "/master-board/quarters/shumen/boyan-bulgarov-2.svg",
  },
  {
    name: "Дивдядово",
    slug: "divdyadovo",
    src: "/master-board/quarters/shumen/divdyadovo.svg",
  },
  {
    name: "Боян Българанов 1",
    slug: "boyan-bulgarov",
    src: "/master-board/quarters/shumen/boyan-bulgarov.svg",
  },
  {
    name: "Пожарната",
    slug: "pozharnata",
    src: "/master-board/quarters/shumen/pozharnata.svg",
  },
  {
    name: "Херсон",
    slug: "herson",
    src: "/master-board/quarters/shumen/herson.svg",
  },
  {
    name: "Под манастира",
    slug: "pod-manastira",
    src: "/master-board/quarters/shumen/pod-manastira.svg",
  },
  {
    name: "Втори корпус",
    slug: "vtori-korpus",
    src: "/master-board/quarters/shumen/vtori-korpus.svg",
  },
  {
    name: "Гривица",
    slug: "grivitsa",
    src: "/master-board/quarters/shumen/grivitsa.svg",
  },
  {
    name: "Дивизионна болница",
    slug: "divizionna-bolnitsa",
    src: "/master-board/quarters/shumen/divizionna-bolnitsa.svg",
  },
  {
    name: "Математическата гимназия",
    slug: "matematicheska-gimnazia",
    src: "/master-board/quarters/shumen/matematicheska-gimnazia.svg",
  },
  {
    name: "Томбул Джамия",
    slug: "tombul-djamia",
    src: "/master-board/quarters/shumen/tombul-djamia.svg",
  },
  {
    name: "Мътница",
    slug: "mtnitsa",
    src: "/master-board/quarters/shumen/mtnitsa.svg",
  },
  {
    name: "Промишлена зона Запад",
    slug: "promishlena-zona-zapad",
    src: "/master-board/quarters/shumen/promishlena-zona-zapad.svg",
  },
  {
    name: "Топхане",
    slug: "tophane",
    src: "/master-board/quarters/shumen/tophane.svg",
  },
  {
    name: "Куршун чешма",
    slug: "kurshun-cheshma",
    src: "/master-board/quarters/shumen/kurshun-cheshma.svg",
  },
  {
    name: "Макак",
    slug: "makak",
    src: "/master-board/quarters/shumen/makak.svg",
  },
  {
    name: "Чашка",
    slug: "chashka",
    src: "/master-board/quarters/shumen/chashka.svg",
  },
  {
    name: "Сакарка",
    slug: "sakarka",
    src: "/master-board/quarters/shumen/sakarka.svg",
  },
  {
    name: "Смесе",
    slug: "smese",
    src: "/master-board/quarters/shumen/smese.svg",
  },
  {
    name: "Промишлена зона Юг",
    slug: "promishlena-zona-yug",
    src: "/master-board/quarters/shumen/promishlena-zona-yug.svg",
  },
  {
    name: "Еверест",
    slug: "everest",
    src: "/master-board/quarters/shumen/everest.svg",
  },
];

export const VARNA_QUARTER_REFS: MasterBoardQuarterRef[] = [
  {
    name: "Ален мак",
    slug: "alen-mak",
    src: "/master-board/quarters/varna/alen-mak.svg",
  },
  {
    name: "Аспарухово",
    slug: "asparuhovo",
    src: "/master-board/quarters/varna/asparuhovo.svg",
  },
  {
    name: "Бриз",
    slug: "briz",
    src: "/master-board/quarters/varna/briz.svg",
  },
  {
    name: "Център",
    slug: "centar",
    src: "/master-board/quarters/varna/centar.svg",
  },
  {
    name: "Чайка",
    slug: "chayka",
    src: "/master-board/quarters/varna/chayka.svg",
  },
  {
    name: "Галата",
    slug: "galata",
    src: "/master-board/quarters/varna/galata.svg",
  },
  {
    name: "Изгрев",
    slug: "izgrev",
    src: "/master-board/quarters/varna/izgrev.svg",
  },
  {
    name: "Кайсиева градина",
    slug: "kaysiyeva-gradina",
    src: "/master-board/quarters/varna/kaysiyeva-gradina.svg",
  },
  {
    name: "Левски",
    slug: "levski",
    src: "/master-board/quarters/varna/levski.svg",
  },
  {
    name: "Лятно кино Тракия",
    slug: "lyatno-kino-trakiya",
    src: "/master-board/quarters/varna/lyatno-kino-trakiya.svg",
  },
  {
    name: "Младост 2",
    slug: "mladost-2",
    src: "/master-board/quarters/varna/mladost-2.svg",
  },
  {
    name: "Младост 1",
    slug: "mladost",
    src: "/master-board/quarters/varna/mladost.svg",
  },
  {
    name: "Пчелина",
    slug: "pchelina",
    src: "/master-board/quarters/varna/pchelina.svg",
  },
  {
    name: "Победа",
    slug: "pobeda",
    src: "/master-board/quarters/varna/pobeda.svg",
  },
  {
    name: "Слънчев ден",
    slug: "slanchev-den",
    src: "/master-board/quarters/varna/slanchev-den.svg",
  },
  {
    name: "Трошево",
    slug: "troshevo",
    src: "/master-board/quarters/varna/troshevo.svg",
  },
  {
    name: "Виница",
    slug: "vinica",
    src: "/master-board/quarters/varna/vinica.svg",
  },
  {
    name: "Владиславово",
    slug: "vladislavovo",
    src: "/master-board/quarters/varna/vladislavovo.svg",
  },
];



export const MASTER_BOARD_SUBTITLE =
  "Редът е: първо всички видими клиентски страници, започвайки от Home Page, след това профилните страници и накрая целият CRM.";

export const MASTER_BOARD_COUNTS = ["15 видими страници", "4 профилни страници", "26 CRM страници"];

export const MASTER_BOARD_FOOTER =
  "Workflow: правим изображение → ти казваш „харесва ми / ОК“ → поставяме точно него в реда → ✓ става зелено → чак тогава страницата влиза за реална React изработка.";

export const MASTER_BOARD_ROWS: MasterBoardRow[] = [
  {
    num: "01",
    category: "Сайт",
    page: "Начална страница",
    path: "/",
    route: "/",
    statusKind: "ok",
    statusLabel: "Одобрена референция",
    approvedByDefault: true,
    desktop: "/master-board/0b93248feb86.png",
    desktopLabel: "Одобрена референция — Начална страница 16:9",
    mobile: "/master-board/1a956ce13232.jpg",
    mobileLabel: "Mobile Design — Начална страница",
  },
  {
    num: "02",
    category: "Сайт",
    page: "Резултати / Оферти",
    path: "/oferti",
    route: "/oferti",
    statusKind: "ok",
    statusLabel: "Одобрени референции",
    approvedByDefault: true,
    desktop: "/master-board/7028048018de.png",
    desktopLabel: "Desktop Design — Резултати",
    mobile: "/master-board/bcf2838b47da.png",
    mobileLabel: "Mobile Design — Резултати",
  },
  {
    num: "03",
    category: "Сайт",
    page: "Всички имоти",
    path: "/properties",
    route: "/properties",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "04",
    category: "Сайт",
    page: "Детайли на имот",
    path: "/property-details",
    route: "/property-details",
    statusKind: "ok",
    statusLabel: "Одобрени референции",
    approvedByDefault: true,
    desktop: "/master-board/3f8a762f2dbf.png",
    desktopLabel: "Desktop Design — Детайли на имот",
    mobile: "/master-board/4f2d17dbe9ed.png",
    mobileLabel: "Mobile Design — Детайли на имот",
  },
  {
    num: "05",
    category: "Сайт",
    page: "Квартали — Шумен",
    path: "/shumen",
    route: "/shumen",
    statusKind: "ok",
    statusLabel: "Одобрени референции",
    approvedByDefault: true,
    desktop: "/master-board/f49034a4e389.jpg",
    desktopLabel: "Desktop Design — Квартали Шумен",
    mobile: "/master-board/442a5e4fce00.jpg",
    mobileLabel: "Mobile Design — Квартали Шумен",
    quarterRefs: SHUMEN_QUARTER_REFS,
  },
  {
    num: "06",
    category: "Сайт",
    page: "Град Варна",
    path: "/varna",
    route: "/varna",
    statusKind: "ok",
    statusLabel: "Референции добавени",
    approvedByDefault: true,
    desktop: "/master-board/2e23e5238cb8.png",
    desktopLabel: "Desktop Design — Варна",
    mobile: "/master-board/5bf7f7dfede5.png",
    mobileLabel: "Mobile Design — Варна",
  },
  {
    num: "07",
    category: "Сайт",
    page: "Град Бургас",
    path: "/burgas",
    route: "/burgas",
    statusKind: "ok",
    statusLabel: "Референции добавени",
    approvedByDefault: true,
    desktop: "/master-board/7e747079d319.png",
    desktopLabel: "Desktop Design — Бургас",
    mobile: "/master-board/8d22cecf2d2b.png",
    mobileLabel: "Mobile Design — Бургас",
  },
  {
    num: "08",
    category: "Сайт",
    page: "Квартал / обща landing страница",
    path: "/neighborhood",
    route: "/neighborhood",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "09",
    category: "Сайт",
    page: "Квартал Бургас — динамична страница",
    path: "/burgas/neighborhood/:areaSlug",
    route: "/burgas/neighborhood/:areaSlug",
    statusKind: "ok",
    statusLabel: "Одобрени референции",
    approvedByDefault: true,
    desktop: "/master-board/6f85d6b5c828.png",
    desktopLabel: "Desktop Design — Бургас — динамична страница на квартал",
    mobile: "/master-board/2b966b5444e0.png",
    mobileLabel: "Mobile Design — Бургас — динамична страница на квартал",
  },
  {
    num: "10",
    category: "Сайт",
    page: "За нас",
    path: "/about",
    route: "/about",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "11",
    category: "Сайт",
    page: "Услуги",
    path: "/services",
    route: "/services",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "12",
    category: "Сайт",
    page: "Инвестиции",
    path: "/investments",
    route: "/investments",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "13",
    category: "Сайт",
    page: "Екип",
    path: "/team",
    route: "/team",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "14",
    category: "Сайт",
    page: "Галерия",
    path: "/gallery",
    route: "/gallery",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "15",
    category: "Сайт",
    page: "Контакти",
    path: "/contact",
    route: "/contact",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "16",
    category: "Профил",
    page: "Вход",
    path: "/login",
    route: "/login",
    statusKind: "ok",
    statusLabel: "Одобрени референции",
    approvedByDefault: true,
    desktop: "/master-board/43dea5b927ff.png",
    desktopLabel: "Desktop Design — CRM Login",
    mobile: "/master-board/437c890cc61f.png",
    mobileLabel: "Mobile Design — CRM Login",
  },
  {
    num: "17",
    category: "Профил",
    page: "Регистрация",
    path: "/register",
    route: "/register",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "18",
    category: "Профил",
    page: "Забравена парола",
    path: "/forgot-password",
    route: "/forgot-password",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "19",
    category: "Профил",
    page: "Нова парола",
    path: "/reset-password",
    route: "/reset-password",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "",
    category: "CRM",
    page: "Варна — динамична страница на квартал",
    path: "/varna/neighborhood/:areaSlug",
    route: "/varna/neighborhood/:areaSlug",
    statusKind: "ok",
    statusLabel: "Одобрени референции",
    approvedByDefault: true,
    desktop: "/master-board/30eba7be5f27.png",
    desktopLabel: "Desktop Design — Варна — динамична страница на квартал",
    mobile: "/master-board/8ae1015e5b64.png",
    mobileLabel: "Mobile Design — Варна — динамична страница на квартал",
  },
  {
    num: "20",
    category: "CRM",
    page: "CRM Табло",
    path: "/crm",
    route: "/crm",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "21",
    category: "CRM",
    page: "Имоти",
    path: "/crm/properties",
    route: "/crm/properties",
    statusKind: "ok",
    statusLabel: "Одобрени референции",
    approvedByDefault: true,
    desktop: "/master-board/3ce49e99b49e.png",
    desktopLabel: "Desktop Design — CRM Имоти",
    mobile: "/master-board/f5fb4e7250aa.png",
    mobileLabel: "Mobile Design — CRM Имоти",
  },
  {
    num: "22",
    category: "CRM",
    page: "AI извлечени имоти",
    path: "/crm/ai-properties",
    route: "/crm/ai-properties",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "23",
    category: "CRM",
    page: "Клиенти / Контакти",
    path: "/crm/clients",
    route: "/crm/clients",
    statusKind: "ok",
    statusLabel: "Desktop референция одобрена",
    approvedByDefault: false,
    desktop: "/master-board/019426929767.png",
    desktopLabel: "Desktop Design — CRM Клиенти / тефтер",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "24",
    category: "CRM",
    page: "Лийдове",
    path: "/crm/leads",
    route: "/crm/leads",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "25",
    category: "CRM",
    page: "Сделки",
    path: "/crm/deals",
    route: "/crm/deals",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "26",
    category: "CRM",
    page: "Активности",
    path: "/crm/activities",
    route: "/crm/activities",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "27",
    category: "CRM",
    page: "Компании",
    path: "/crm/companies",
    route: "/crm/companies",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "28",
    category: "CRM",
    page: "Брокери",
    path: "/crm/brokers",
    route: "/crm/brokers",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "29",
    category: "CRM",
    page: "Договори",
    path: "/crm/contracts",
    route: "/crm/contracts",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "30",
    category: "CRM",
    page: "Наеми & плащания",
    path: "/crm/rent-management",
    route: "/crm/rent-management",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "31",
    category: "CRM",
    page: "Автоматизации",
    path: "/crm/automations",
    route: "/crm/automations",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "32",
    category: "CRM",
    page: "AI Асистент",
    path: "/crm/assistant",
    route: "/crm/assistant",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "33",
    category: "CRM",
    page: "AI агент за обяви",
    path: "/crm/sourcing-agent",
    route: "/crm/sourcing-agent",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "34",
    category: "CRM",
    page: "Facebook имотен агент",
    path: "/crm/facebook-agent",
    route: "/crm/facebook-agent",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "35",
    category: "CRM",
    page: "Facebook клиенти",
    path: "/crm/facebook-clients",
    route: "/crm/facebook-clients",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "36",
    category: "CRM",
    page: "Заявки",
    path: "/crm/requests",
    route: "/crm/requests",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "37",
    category: "CRM",
    page: "Качи обява",
    path: "/crm/upload",
    route: "/crm/upload",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "38",
    category: "CRM",
    page: "Карта на имотите",
    path: "/crm/map",
    route: "/crm/map",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "39",
    category: "CRM",
    page: "Календар",
    path: "/crm/calendar",
    route: "/crm/calendar",
    statusKind: "ok",
    statusLabel: "Desktop референция одобрена",
    approvedByDefault: false,
    desktop: "/master-board/32fdf66f9162.png",
    desktopLabel: "Desktop — седмичен календар Понеделник–Петък, 07:00–19:00",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "40",
    category: "CRM",
    page: "Банки / ипотеки",
    path: "/crm/bank",
    route: "/crm/bank",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "41",
    category: "CRM",
    page: "Съобщения",
    path: "/crm/messages",
    route: "/crm/messages",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "42",
    category: "CRM",
    page: "Анализи / отчети",
    path: "/crm/reports",
    route: "/crm/reports",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "43",
    category: "CRM",
    page: "Настройки",
    path: "/crm/settings",
    route: "/crm/settings",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "44",
    category: "CRM",
    page: "Фактури",
    path: "/crm/invoices",
    route: "/crm/invoices",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
  {
    num: "45",
    category: "CRM",
    page: "Оферти",
    path: "/crm/estimates",
    route: "/crm/estimates",
    statusKind: "waiting",
    statusLabel: "Чака референция",
    approvedByDefault: false,
    desktop: null,
    desktopLabel: "Няма одобрена визуализация",
    mobile: null,
    mobileLabel: "Няма одобрена Mobile визуализация",
  },
];
