/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties.$propertyId'
import { Route as CitiesSlugRouteImport } from './routes/cities.$slug'
import { Route as AdminPropertiesRouteImport } from './routes/admin.properties'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as CitiesSlugDistrictsDistrictRouteImport } from './routes/cities.$slug.districts.$district'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesSlugRoute = CitiesSlugRouteImport.update({
  id: '/cities/$slug',
  path: '/cities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const CitiesSlugDistrictsDistrictRoute =
  CitiesSlugDistrictsDistrictRouteImport.update({
    id: '/districts/$district',
    path: '/districts/$district',
    getParentRoute: () => CitiesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/cities/$slug': typeof CitiesSlugRouteWithChildren
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cities/$slug/districts/$district': typeof CitiesSlugDistrictsDistrictRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/cities/$slug': typeof CitiesSlugRouteWithChildren
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/admin': typeof AdminIndexRoute
  '/cities/$slug/districts/$district': typeof CitiesSlugDistrictsDistrictRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/cities/$slug': typeof CitiesSlugRouteWithChildren
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cities/$slug/districts/$district': typeof CitiesSlugDistrictsDistrictRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/ai'
    | '/admin/inquiries'
    | '/admin/properties'
    | '/cities/$slug'
    | '/properties/$propertyId'
    | '/admin/'
    | '/cities/$slug/districts/$district'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/ai'
    | '/admin/inquiries'
    | '/admin/properties'
    | '/cities/$slug'
    | '/properties/$propertyId'
    | '/admin'
    | '/cities/$slug/districts/$district'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/ai'
    | '/admin/inquiries'
    | '/admin/properties'
    | '/cities/$slug'
    | '/properties/$propertyId'
    | '/admin/'
    | '/cities/$slug/districts/$district'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  CitiesSlugRoute: typeof CitiesSlugRouteWithChildren
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$slug': {
      id: '/cities/$slug'
      path: '/cities/$slug'
      fullPath: '/cities/$slug'
      preLoaderRoute: typeof CitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cities/$slug/districts/$district': {
      id: '/cities/$slug/districts/$district'
      path: '/districts/$district'
      fullPath: '/cities/$slug/districts/$district'
      preLoaderRoute: typeof CitiesSlugDistrictsDistrictRouteImport
      parentRoute: typeof CitiesSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CitiesSlugRouteChildren {
  CitiesSlugDistrictsDistrictRoute: typeof CitiesSlugDistrictsDistrictRoute
}

const CitiesSlugRouteChildren: CitiesSlugRouteChildren = {
  CitiesSlugDistrictsDistrictRoute: CitiesSlugDistrictsDistrictRoute,
}

const CitiesSlugRouteWithChildren = CitiesSlugRoute._addFileChildren(
  CitiesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  CitiesSlugRoute: CitiesSlugRouteWithChildren,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
