/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties.$propertyId'
import { Route as CitiesSlugRouteImport } from './routes/cities.$slug'
import { Route as AdminQuartersRouteImport } from './routes/admin.quarters'
import { Route as AdminPropertiesRouteImport } from './routes/admin.properties'
import { Route as AdminMatchesRouteImport } from './routes/admin.matches'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminExtractedRouteImport } from './routes/admin.extracted'
import { Route as AdminContractsRouteImport } from './routes/admin.contracts'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminCitiesRouteImport } from './routes/admin.cities'
import { Route as AdminBrokersRouteImport } from './routes/admin.brokers'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as CitiesSlugDistrictsDistrictRouteImport } from './routes/cities.$slug.districts.$district'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesSlugRoute = CitiesSlugRouteImport.update({
  id: '/cities/$slug',
  path: '/cities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuartersRoute = AdminQuartersRouteImport.update({
  id: '/quarters',
  path: '/quarters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchesRoute = AdminMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExtractedRoute = AdminExtractedRouteImport.update({
  id: '/extracted',
  path: '/extracted',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContractsRoute = AdminContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrokersRoute = AdminBrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const CitiesSlugDistrictsDistrictRoute =
  CitiesSlugDistrictsDistrictRouteImport.update({
    id: '/districts/$district',
    path: '/districts/$district',
    getParentRoute: () => CitiesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brokers': typeof AdminBrokersRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/extracted': typeof AdminExtractedRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/quarters': typeof AdminQuartersRoute
  '/cities/$slug': typeof CitiesSlugRouteWithChildren
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cities/$slug/districts/$district': typeof CitiesSlugDistrictsDistrictRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brokers': typeof AdminBrokersRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/extracted': typeof AdminExtractedRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/quarters': typeof AdminQuartersRoute
  '/cities/$slug': typeof CitiesSlugRouteWithChildren
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/admin': typeof AdminIndexRoute
  '/cities/$slug/districts/$district': typeof CitiesSlugDistrictsDistrictRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/brokers': typeof AdminBrokersRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/contracts': typeof AdminContractsRoute
  '/admin/extracted': typeof AdminExtractedRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/quarters': typeof AdminQuartersRoute
  '/cities/$slug': typeof CitiesSlugRouteWithChildren
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cities/$slug/districts/$district': typeof CitiesSlugDistrictsDistrictRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/search'
    | '/admin/ai'
    | '/admin/audit'
    | '/admin/brokers'
    | '/admin/cities'
    | '/admin/clients'
    | '/admin/contracts'
    | '/admin/extracted'
    | '/admin/inquiries'
    | '/admin/matches'
    | '/admin/properties'
    | '/admin/quarters'
    | '/cities/$slug'
    | '/properties/$propertyId'
    | '/admin/'
    | '/cities/$slug/districts/$district'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/search'
    | '/admin/ai'
    | '/admin/audit'
    | '/admin/brokers'
    | '/admin/cities'
    | '/admin/clients'
    | '/admin/contracts'
    | '/admin/extracted'
    | '/admin/inquiries'
    | '/admin/matches'
    | '/admin/properties'
    | '/admin/quarters'
    | '/cities/$slug'
    | '/properties/$propertyId'
    | '/admin'
    | '/cities/$slug/districts/$district'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/search'
    | '/admin/ai'
    | '/admin/audit'
    | '/admin/brokers'
    | '/admin/cities'
    | '/admin/clients'
    | '/admin/contracts'
    | '/admin/extracted'
    | '/admin/inquiries'
    | '/admin/matches'
    | '/admin/properties'
    | '/admin/quarters'
    | '/cities/$slug'
    | '/properties/$propertyId'
    | '/admin/'
    | '/cities/$slug/districts/$district'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  CitiesSlugRoute: typeof CitiesSlugRouteWithChildren
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$slug': {
      id: '/cities/$slug'
      path: '/cities/$slug'
      fullPath: '/cities/$slug'
      preLoaderRoute: typeof CitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quarters': {
      id: '/admin/quarters'
      path: '/quarters'
      fullPath: '/admin/quarters'
      preLoaderRoute: typeof AdminQuartersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matches': {
      id: '/admin/matches'
      path: '/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AdminMatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/extracted': {
      id: '/admin/extracted'
      path: '/extracted'
      fullPath: '/admin/extracted'
      preLoaderRoute: typeof AdminExtractedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contracts': {
      id: '/admin/contracts'
      path: '/contracts'
      fullPath: '/admin/contracts'
      preLoaderRoute: typeof AdminContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cities': {
      id: '/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brokers': {
      id: '/admin/brokers'
      path: '/brokers'
      fullPath: '/admin/brokers'
      preLoaderRoute: typeof AdminBrokersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cities/$slug/districts/$district': {
      id: '/cities/$slug/districts/$district'
      path: '/districts/$district'
      fullPath: '/cities/$slug/districts/$district'
      preLoaderRoute: typeof CitiesSlugDistrictsDistrictRouteImport
      parentRoute: typeof CitiesSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBrokersRoute: typeof AdminBrokersRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminContractsRoute: typeof AdminContractsRoute
  AdminExtractedRoute: typeof AdminExtractedRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminMatchesRoute: typeof AdminMatchesRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminQuartersRoute: typeof AdminQuartersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBrokersRoute: AdminBrokersRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminContractsRoute: AdminContractsRoute,
  AdminExtractedRoute: AdminExtractedRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminMatchesRoute: AdminMatchesRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminQuartersRoute: AdminQuartersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CitiesSlugRouteChildren {
  CitiesSlugDistrictsDistrictRoute: typeof CitiesSlugDistrictsDistrictRoute
}

const CitiesSlugRouteChildren: CitiesSlugRouteChildren = {
  CitiesSlugDistrictsDistrictRoute: CitiesSlugDistrictsDistrictRoute,
}

const CitiesSlugRouteWithChildren = CitiesSlugRoute._addFileChildren(
  CitiesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  CitiesSlugRoute: CitiesSlugRouteWithChildren,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
