/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties.$propertyId'
import { Route as CitiesSlugRouteImport } from './routes/cities.$slug'
import { Route as CitiesSlugDistrictsDistrictRouteImport } from './routes/cities.$slug.districts.$district'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesSlugRoute = CitiesSlugRouteImport.update({
  id: '/cities/$slug',
  path: '/cities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesSlugDistrictsDistrictRoute =
  CitiesSlugDistrictsDistrictRouteImport.update({
    id: '/districts/$district',
    path: '/districts/$district',
    getParentRoute: () => CitiesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cities/$slug': typeof CitiesSlugRouteWithChildren
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/cities/$slug/districts/$district': typeof CitiesSlugDistrictsDistrictRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cities/$slug': typeof CitiesSlugRouteWithChildren
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/cities/$slug/districts/$district': typeof CitiesSlugDistrictsDistrictRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cities/$slug': typeof CitiesSlugRouteWithChildren
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/cities/$slug/districts/$district': typeof CitiesSlugDistrictsDistrictRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cities/$slug'
    | '/properties/$propertyId'
    | '/cities/$slug/districts/$district'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cities/$slug'
    | '/properties/$propertyId'
    | '/cities/$slug/districts/$district'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/cities/$slug'
    | '/properties/$propertyId'
    | '/cities/$slug/districts/$district'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CitiesSlugRoute: typeof CitiesSlugRouteWithChildren
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$slug': {
      id: '/cities/$slug'
      path: '/cities/$slug'
      fullPath: '/cities/$slug'
      preLoaderRoute: typeof CitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$slug/districts/$district': {
      id: '/cities/$slug/districts/$district'
      path: '/districts/$district'
      fullPath: '/cities/$slug/districts/$district'
      preLoaderRoute: typeof CitiesSlugDistrictsDistrictRouteImport
      parentRoute: typeof CitiesSlugRoute
    }
  }
}

interface CitiesSlugRouteChildren {
  CitiesSlugDistrictsDistrictRoute: typeof CitiesSlugDistrictsDistrictRoute
}

const CitiesSlugRouteChildren: CitiesSlugRouteChildren = {
  CitiesSlugDistrictsDistrictRoute: CitiesSlugDistrictsDistrictRoute,
}

const CitiesSlugRouteWithChildren = CitiesSlugRoute._addFileChildren(
  CitiesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CitiesSlugRoute: CitiesSlugRouteWithChildren,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
